### 10
POST http://localhost:8080/file/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="ts.zip"

< ./ts10.zip
--WebAppBoundary--